version: "3.7"
services:
 db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: 'root'
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: 'root'
     MYSQL_DATABASE: WebOps_development
   ports:
      - "3307:3306"
 redis:
   image: "redis:4.0-alpine"
   command: redis-server
   volumes:
      - "redis:/data"

 website:
   depends_on:
      - "db"
      - "redis"
   build: .
   ports:
      - "3000:3000"
   environment:
     DB_HOST: db
     RAILS_ENV: development
   volumes:
      - ".:/app"
      - "./config/docker/database.yml:/app/config/database.yml"
 sidekiq:
   depends_on:
      - "redis"
   build: .
   command: bundle exec sidekiq
   volumes:
      - ".:/app"
   environment:
     REDIS_URL: redis://redis:6379/12
     RAILS_ENV: development

volumes:
 redis:
 db: