default: &default
 adapter: mysql2
 encoding: utf8mb4
 pool: 5
 username: root
 password: 'root'
 port: 3306
 host: <%= ENV['DB_HOST'] %>
 socket: /var/run/mysqld/mysqld.sock
 
development:
 <<: *default
 database: WebOps_development

production:
 <<: *default
 database: <%= ENV['DB_DATABASE'] %>